{
 "title": "Tracker Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Detections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_rules_detections_total" }
   ]
  },
  {
   "title": "Signatures Loaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_rules_signatures_total" }
   ]
  },
  {
   "title": "Events Throughput",
   "type": "timeseries",
   "description": "The rate of events processed and lost",
   "gridPos": { "h": 18, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "rate(tracee_ebpf_events_total[10s])",
     "legendFormat": "events/sec"
    },
    {
     "expr": "rate(tracee_ebpf_lostevents_total[10s])",
     "legendFormat": "lost_events/sec"
    }
   ]
  },
  {
   "title": "EBPF Events Produced",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_ebpf_events_total" }
   ]
  },
  {
   "title": "Lost Events",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tracee_ebpf_lostevents_total", "legendFormat": "Buffer Lost Events" },
    {
     "expr": "tracee_ebpf_network_lostevents_total",
     "legendFormat": "Network Lost Events"
    },
    {
     "expr": "tracee_ebpf_write_lostevents_total",
     "legendFormat": "Write Lost Events"
    }
   ]
  }
 ]
}